language: node_js
node_js: '10'
sudo: false
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules

script: "npm run-script test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
